require_relative('../models/tag')
require_relative('../models/merchant')
require_relative('../models/budget')
# require_relative('../models/transaction')

# Transaction.delete_all()
Merchant.delete_all()
Tag.delete_all()
Budget.delete_all()

tag0 = Tag.new({'name' => ''})
tag0.save()
merchant0 = Merchant.new({'name' => ''})
merchant0.save()
budget0 = Budget.new({'name' => '', 'amount' => nil, 'alert_limit' => nil})
budget0.save()